# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  dbkit_tables:
    import: "package:dbkit_gen/builder.dart"
    builder_factories: ["dbkitTablesBuilder"]
    build_extensions: {".dart": ["dbkit.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
