import 'schema.dart';

/// Emits one part-file fragment for a single `@DbTable` model.
///
/// This is a fragment, not a library: no imports (the part file shares its
/// owner's `package:dbkit/dbkit.dart` import) and no `part of` header —
/// `source_gen`'s `PartBuilder` adds that. [targets] maps relation target
/// table names to their schemas (model names + columns).
String emitTablePart(
  TableSchema table, {
  required Map<String, TableSchema> targets,
  required String source,
}) {
  final e = _Emitter(table, targets, source);
  return e.emit();
}

/// `user_id` -> `userId`. Shared with the resolver's validation.
String camelCase(String s) {
  final parts = s.split('_').where((p) => p.isNotEmpty).toList();
  if (parts.isEmpty) return s;
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

class _Emitter {
  final TableSchema t;
  final Map<String, TableSchema> targets;
  final String source;
  final StringBuffer _out = StringBuffer();

  _Emitter(this.t, this.targets, this.source);

  void _line([String s = '']) => _out.writeln(s);

  /// Emits a braced `if` (keeps generated code lint-clean).
  void _guarded(String cond, String body) {
    _line('    if ($cond) {');
    _line('      $body');
    _line('    }');
  }

  TableSchema _target(RelationSchema r) => targets[r.table]!;

  String emit() {
    _line('// Generated by dbkit_gen from $source. Do not edit; re-run:');
    _line('//   dart run build_runner build');
    _line('');
    _emitColumns();
    _line('');
    _emitMapping();
    _line('');
    for (final r in t.relations) {
      _emitWrapper(r);
      _line('');
    }
    _emitTableClass();
    _line('');
    _emitModelRelations();
    _line('');
    _emitDbExtension();
    _line('');
    _emitCreateTable();
    _line('');
    _emitDropTable();
    _line('');
    _emitRegisterRelations();
    _line('');
    _emitHelpers();
    return _out.toString();
  }

  // -- columns ---------------------------------------------------------------

  void _emitColumns() {
    _line('/// Column names of `${t.name}` for refactor-safe queries:');
    _line('/// `db.${camelCase(t.name)}.ref.where((w) => w.eq(${t.model}Columns.age, 18))`.');
    _line('abstract final class ${t.model}Columns {');
    for (final c in t.columns) {
      _line("  static const ${c.field} = '${c.name}';");
    }
    _line('}');
  }

  String _dartType(ColumnSchema c) {
    final base = switch (c.type) {
      ColumnType.integer => 'int',
      ColumnType.text => 'String',
      ColumnType.real => 'double',
      ColumnType.boolean => 'bool',
      ColumnType.datetime => 'DateTime',
      ColumnType.blob => 'Uint8List',
    };
    if (c.autoIncrement) return '$base?';
    return c.nonNull ? base : '$base?';
  }

  // -- mapping glue (user writes `=> _\$XFromMap(map)` / `=> _\$XToMap(this)`) --

  void _emitMapping() {
    final m = t.model;
    final cols = t.columns;
    _line('/// Reads [$m] from a database row. Used by `$m.fromMap`.');
    _line('$m _\$${m}FromMap(Map<String, Object?> map) =>');
    _line('    $m(');
    for (final c in cols) {
      _line('      ${c.field}: ${_fromMapExpr(c)},');
    }
    _line('    );');
    _line('');
    _line('/// Writes [$m] to a database row. Used by `$m.toMap`.');
    _line('Map<String, Object?> _\$${m}ToMap($m value) => {');
    for (final c in cols) {
      _line("      '${c.name}': ${_toMapFieldExpr(c)},");
    }
    _line('};');
  }

  String _fromMapExpr(ColumnSchema c) {
    final access = "map['${c.name}']";
    final nullable = _dartType(c).endsWith('?');
    switch (c.type) {
      case ColumnType.integer:
        return nullable ? '$access as int?' : '$access as int';
      case ColumnType.text:
        return nullable ? '$access as String?' : '$access as String';
      case ColumnType.real:
        return nullable
            ? '($access as num?)?.toDouble()'
            : '($access as num).toDouble()';
      case ColumnType.boolean:
        return nullable
            ? '$access == null ? null : ($access == 1 || $access == true)'
            : '($access == 1 || $access == true)';
      case ColumnType.datetime:
        return nullable
            ? '$access == null ? null : DateTime.parse($access as String)'
            : 'DateTime.parse($access as String)';
      case ColumnType.blob:
        return nullable
            ? '$access as Uint8List?'
            : '$access as Uint8List';
    }
  }

  String _toMapFieldExpr(ColumnSchema c) {
    if (c.type == ColumnType.datetime) {
      return _dartType(c).endsWith('?')
          ? 'value.${c.field}?.toIso8601String()'
          : 'value.${c.field}.toIso8601String()';
    }
    return 'value.${c.field}';
  }

  String _dartLiteral(Object? v) {
    if (v == null) return 'null';
    if (v is bool || v is num) return '$v';
    return "'${v.toString().replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
  }

  // -- relation wrappers ---------------------------------------------------------

  String _wrapperName(RelationSchema r) =>
      '${t.model}With${_cap(_relProp(r.name))}';

  /// The Dart type held under the relation key after eager loading.
  String _relatedType(RelationSchema r) {
    final target = _target(r).model;
    return switch (r.kind) {
      RelationKind.hasMany || RelationKind.belongsToMany => 'List<$target>',
      RelationKind.hasOne || RelationKind.belongsTo => '$target?',
    };
  }

  String _relatedFromMap(RelationSchema r, String keyExpr) {
    final target = _target(r).model;
    switch (r.kind) {
      case RelationKind.hasMany:
      case RelationKind.belongsToMany:
        return '[for (final m in ($keyExpr as List)) $target.fromMap((m as Map).cast<String, Object?>())]';
      case RelationKind.hasOne:
      case RelationKind.belongsTo:
        return '$keyExpr == null ? null : $target.fromMap(($keyExpr as Map).cast<String, Object?>())';
    }
  }

  void _emitWrapper(RelationSchema r) {
    final wrapper = _wrapperName(r);
    final prop = _relProp(r.name);
    final modelVar = '${t.model[0].toLowerCase()}${t.model.substring(1)}';
    final kindDoc = switch (r.kind) {
      RelationKind.hasMany => 'their $prop',
      RelationKind.hasOne => 'their $prop',
      RelationKind.belongsTo => 'its $prop',
      RelationKind.belongsToMany => 'their $prop',
    };
    _line('/// A ${t.model.toLowerCase()} with $kindDoc eagerly loaded.');
    _line('/// See [${t.model}Table.with${_cap(prop)}].');
    _line('class $wrapper {');
    _line('  final ${t.model} $modelVar;');
    _line('  final ${_relatedType(r)} $prop;');
    _line('  const $wrapper({required this.$modelVar, required this.$prop});');
    _line('');
    _line('  @override');
    _line(
        '  String toString() => \'$wrapper($modelVar: \$$modelVar, $prop: \$$prop)\';');
    _line('}');
  }

  String _cap(String s) => s[0].toUpperCase() + s.substring(1);

  /// Dart member name for a relation (`blog_posts` -> `blogPosts`).
  String _relProp(String relation) => camelCase(relation);

  // -- table repository ------------------------------------------------------------

  List<ColumnSchema> _pkColumns() =>
      t.columns.where((c) => c.primaryKey).toList();

  void _emitTableClass() {
    final m = t.model;
    final pks = _pkColumns();
    final singlePk = pks.length == 1 ? pks.first : null;
    final pkAuto = singlePk != null && singlePk.autoIncrement;
    final pkCol = singlePk?.name ?? 'id';
    final pkField = singlePk?.field ?? 'id';
    final nn = '_withoutNulls$m';

    _line('/// Typed queries for `${t.name}`.');
    _line('class ${m}Table {');
    _line('  final Db _db;');
    _line('  const ${m}Table(this._db);');
    _line('');
    _line('  /// Raw handle for custom queries: `table.ref.where(...)...`.');
    _line("  TableRef get ref => _db.table('${t.name}');");
    _line('');
    _line('  Future<List<$m>> all({String? orderBy, bool desc = false, int? limit, int? offset}) =>');
    _line('      list(orderBy: orderBy, desc: desc, limit: limit, offset: offset);');
    _line('');
    _line('  Future<List<$m>> list({Condition Function(Where w)? where, String? orderBy, bool desc = false, int? limit, int? offset}) async {');
    _line('    var q = ref.query();');
    _guarded('where != null', 'q = q.where(where);');
    _guarded('orderBy != null', 'q = q.orderBy(orderBy, desc: desc);');
    _guarded('limit != null', 'q = q.limit(limit);');
    _guarded('offset != null', 'q = q.offset(offset);');
    _line('    return [for (final m in await q.get()) $m.fromMap(m)];');
    _line('  }');
    _line('');
    _line('  Future<$m?> findById(Object id) async {');
    _line('    final m = await ref.findById(id, idColumn: \'$pkCol\');');
    _line('    return m == null ? null : $m.fromMap(m);');
    _line('  }');
    _line('');
    _line('  Future<$m> findByIdOrFail(Object id) async =>');
    _line("      $m.fromMap(await ref.findByIdOrFail(id, idColumn: '$pkCol'));");
    _line('');
    _line('  Future<$m?> findOne(Condition Function(Where w) where) async {');
    _line('    final m = await ref.findOneWhere(where);');
    _line('    return m == null ? null : $m.fromMap(m);');
    _line('  }');
    _line('');
    _line('  Future<int> count([Condition Function(Where w)? where]) => ref.count(where);');
    _line('');
    _line('  Future<bool> exists(Condition Function(Where w) where) => ref.existsWhere(where);');
    _line('');
    _line('  /// Inserts and returns the new row id. Null fields are omitted so');
    _line('  /// autoincrement ids and DB defaults apply.');
    _line('  Future<int> insert($m value) => ref.insert($nn(value.toMap()));');
    _line('');
    _line('  Future<void> insertMany(Iterable<$m> values) =>');
    _line('      ref.insertMany([for (final v in values) $nn(v.toMap())]);');
    _line('');
    if (pkAuto) {
      _line('  /// Inserts [value] when id is null (returning the saved row),');
      _line('  /// or upserts when id is already set.');
      _line('  Future<$m> save($m value) async {');
      _line('    final id = value.$pkField;');
      _line('    if (id == null) {');
      _line('      final newId = await insert(value);');
      _line('      return await findByIdOrFail(newId);');
      _line('    } else {');
      _line('      await ref.upsert(value.toMap());');
      _line('      return value;');
      _line('    }');
      _line('  }');
    } else if (singlePk != null) {
      _line('  /// Inserts [value], or replaces the row when its id is already set.');
      _line('  Future<void> save($m value) => ref.upsert(value.toMap());');
    } else {
      _line('  /// Inserts [value] (this table has no single primary key).');
      _line('  Future<int> save($m value) => insert(value);');
    }
    _line('');
    if (singlePk != null) {
      if (pkAuto) {
        _line('  /// Updates the row matching [value.$pkField]. Null fields are left untouched —');
        _line('  /// use [ref] with an explicit map to write NULL.');
        _line('  Future<int> update($m value) {');
        _line('    final id = value.$pkField;');
        _line("    if (id == null) {");
        _line("      throw ArgumentError.value(value, 'value', '$pkField must be set to update');");
        _line('    }');
        _line("    final values = $nn(value.toMap())..remove('$pkCol');");
        _line("    return ref.updateById(id, values, idColumn: '$pkCol');");
        _line('  }');
        _line('');
      } else {
        _line('  /// Updates the row matching [value.$pkField].');
        _line('  Future<int> update($m value) {');
        _line("    final values = $nn(value.toMap())..remove('$pkCol');");
        _line("    return ref.updateById(value.$pkField, values, idColumn: '$pkCol');");
        _line('  }');
        _line('');
      }
      _line("  Future<int> updateById(Object id, Map<String, Object?> values) => ref.updateById(id, values, idColumn: '$pkCol');");
      _line('');
      _line("  Future<int> deleteById(Object id) => ref.deleteById(id, idColumn: '$pkCol');");
      _line('');
    }
    _line('  Future<int> deleteWhere(Condition Function(Where w) where) => ref.deleteWhere(where);');
    for (final r in t.relations) {
      _line('');
      _emitWithMethod(r);
    }
    _line('}');
  }

  void _emitWithMethod(RelationSchema r) {
    final m = t.model;
    final wrapper = _wrapperName(r);
    final prop = _relProp(r.name);
    final method = 'with${_cap(prop)}';
    final modelVar = '${m[0].toLowerCase()}${m.substring(1)}';
    final keyAccess = "r['${r.name}']";
    _line('  /// Eager-loads `${r.name}` for every matching row.');
    _line('  Future<List<$wrapper>> $method({Condition Function(Where w)? where, void Function(SelectQuery q)? constrain, String? orderBy, bool desc = false, int? limit, int? offset}) async {');
    if (r.kind == RelationKind.hasMany || r.kind == RelationKind.belongsToMany) {
      _line("    var q = ref.withMany('${r.name}', constrain);");
    } else {
      _line("    var q = ref.withOne('${r.name}', constrain);");
    }
    _guarded('where != null', 'q = q.where(where);');
    _guarded('orderBy != null', 'q = q.orderBy(orderBy, desc: desc);');
    _guarded('limit != null', 'q = q.limit(limit);');
    _guarded('offset != null', 'q = q.offset(offset);');
    _line('    final rows = await q.get();');
    _line('    return [');
    _line('      for (final r in rows)');
    _line('        $wrapper(');
    _line('          $modelVar: $m.fromMap(r),');
    _line('          $prop: ${_relatedFromMap(r, keyAccess)},');
    _line('        ),');
    _line('    ];');
    _line('  }');
  }

  // -- model relation loaders --------------------------------------------------------

  void _emitModelRelations() {
    if (t.relations.isEmpty) return;
    _line('/// Relationship accessors for [${t.model}].');
    _line('extension ${t.model}Relations on ${t.model} {');
    for (final r in t.relations) {
      _emitLoader(r);
    }
    _line('}');
  }

  void _emitLoader(RelationSchema r) {
    final target = _target(r);
    final tm = target.model;
    final targetGetter = camelCase(r.table);
    final prop = _relProp(r.name);
    final localField = _ffield(r.localKey);
    switch (r.kind) {
      case RelationKind.hasMany:
        _line('  /// ${tm}s belonging to this ${t.model.toLowerCase()} ([] when `$localField` is null).');
        _line('  Future<List<$tm>> $prop(Db db) async {');
        _line('    final key = $localField;');
        _guarded('key == null', 'return [];');
        _line("    final rows = await db.$targetGetter.ref.where((w) => w.eq('${r.foreignKey}', key)).get();");
        _line('    return [for (final m in rows) $tm.fromMap(m)];');
        _line('  }');
      case RelationKind.hasOne:
        _line('  /// The $prop of this ${t.model.toLowerCase()}, or null.');
        _line('  Future<$tm?> $prop(Db db) async {');
        _line('    final key = $localField;');
        _guarded('key == null', 'return null;');
        _line("    final rows = await db.$targetGetter.ref.where((w) => w.eq('${r.foreignKey}', key)).limit(1).get();");
        _line('    return rows.isEmpty ? null : $tm.fromMap(rows.first);');
        _line('  }');
      case RelationKind.belongsTo:
        final fkField = _ffield(r.foreignKey!);
        final fkNullable = _nullable(r.foreignKey!);
        _line('  /// The $prop this ${t.model.toLowerCase()} belongs to, or null.');
        _line('  Future<$tm?> $prop(Db db) async {');
        _line('    final fk = $fkField;');
        if (fkNullable) _guarded('fk == null', 'return null;');
        if (r.targetKey == 'id') {
          _line('    final m = await db.$targetGetter.ref.findById(fk);');
        } else {
          _line("    final m = await db.$targetGetter.ref.findOneWhere((w) => w.eq('${r.targetKey}', fk));");
        }
        _line('    return m == null ? null : $tm.fromMap(m);');
        _line('  }');
      case RelationKind.belongsToMany:
        final pivotGetter = camelCase(r.pivot!);
        // singular for add/remove: strip one trailing 's'
        final single = prop.endsWith('s') && prop.length > 1
            ? prop.substring(0, prop.length - 1)
            : prop;
        final singleCap = _cap(single);
        final tidField = _tfield(target, r.targetKey);
        final tidNullable =
            _dartType(target.column(r.targetKey)!).endsWith('?');
        _line('  /// ${tm}s linked to this ${t.model.toLowerCase()} via `${r.pivot}`.');
        _line('  Future<List<$tm>> $prop(Db db) async {');
        _line('    final key = $localField;');
        _guarded('key == null', 'return [];');
        _line("    final pivots = await db.$pivotGetter.ref.where((w) => w.eq('${r.pivotFromKey}', key)).get();");
        _line("    final ids = <Object?>[for (final p in pivots) p['${r.pivotToKey}']];");
        _guarded('ids.isEmpty', 'return [];');
        _line("    final rows = await db.$targetGetter.ref.where((w) => w.inList('${r.targetKey}', ids)).get();");
        _line('    return [for (final m in rows) $tm.fromMap(m)];');
        _line('  }');
        _line('');
        _line('  /// Links [other] to this ${t.model.toLowerCase()}.');
        _line('  Future<void> add$singleCap(Db db, $tm other) async {');
        _line('    final pid = $localField;');
        _line('    final tid = other.$tidField;');
        _line('    if (pid == null${tidNullable ? ' || tid == null' : ''}) {');
        _line("      throw StateError('Cannot link ${t.model} with null id');");
        _line('    }');
        _line("    await db.$pivotGetter.ref.insert({'${r.pivotFromKey}': pid, '${r.pivotToKey}': tid});");
        _line('  }');
        _line('');
        _line('  /// Unlinks [other] from this ${t.model.toLowerCase()}.');
        _line('  Future<void> remove$singleCap(Db db, $tm other) async {');
        _line('    final pid = $localField;');
        _line('    final tid = other.$tidField;');
        _guarded(
            'pid == null${tidNullable ? ' || tid == null' : ''}', 'return;');
        _line('    await db.$pivotGetter.deleteWhere(');
        _line("      (w) => w.eq('${r.pivotFromKey}', pid) & w.eq('${r.pivotToKey}', tid),");
        _line('    );');
        _line('  }');
        _line('');
    }
  }

  /// Dart field for a *database* column name on [t].
  String _ffield(String dbName) => t.column(dbName)!.field;

  /// Dart field for a *database* column name on [target].
  String _tfield(TableSchema target, String dbName) =>
      target.column(dbName)!.field;

  bool _nullable(String dbName) =>
      _dartType(t.column(dbName)!).endsWith('?');

  // -- per-table db access + setup -----------------------------------------------------

  void _emitDbExtension() {
    _line('/// Typed table accessor. Other generated parts add their own.');
    _line('extension Db${t.model}Table on Db {');
    _line('  ${t.model}Table get ${camelCase(t.name)} => ${t.model}Table(this);');
    _line('}');
    _line('');
  }

  void _emitColumnStmt(ColumnSchema c) {
    final method = c.type.name;
    final sb = StringBuffer("    t.$method('${c.name}')");
    if (c.autoIncrement) {
      sb.write('.autoInc()');
    } else {
      if (c.primaryKey) sb.write('.primary()');
      if (c.nonNull && !c.primaryKey) sb.write('.notNull()');
      if (c.unique) sb.write('.isUnique()');
      if (c.defaultNow) {
        sb.write('.defaultsToNow()');
      } else if (c.defaultValue != null) {
        sb.write('.defaultsTo(${_dartLiteral(c.defaultValue)})');
      }
      final ref = c.references;
      if (ref != null) {
        sb.write(
            ".referencesTable('${ref.table}', '${ref.column}', onDelete: '${ref.onDelete}', onUpdate: '${ref.onUpdate}')");
      }
    }
    sb.write(';');
    _line(sb.toString());
  }

  void _emitCreateTable() {
    _line('/// Creates the `${t.name}` table (plus indexes).');
    _line('Future<void> create${t.model}Table(Db db) async {');
    _line("  await db.createTable('${t.name}', (t) {");
    for (final c in t.columns) {
      _emitColumnStmt(c);
    }
    final compositePk =
        t.columns.where((c) => c.primaryKey && !c.autoIncrement).toList();
    if (compositePk.length > 1) {
      _line("    t.primary([${compositePk.map((c) => "'${c.name}'").join(', ')}]);");
    }
    for (final c in t.columns) {
      if (c.check != null) {
        _line('    t.check(${_dartLiteral(c.check)});');
      }
    }
    if (t.timestamps) _line('    t.timestamps();');
    for (final idx in t.indexes) {
      final cols = idx.columns.map((f) => "'${_dbName(t, f)}'").join(', ');
      if (idx.name == null && !idx.unique) {
        _line('    t.index([$cols]);');
      } else if (idx.name == null) {
        _line('    t.index([$cols], unique: true);');
      } else if (!idx.unique) {
        _line("    t.index([$cols], name: '${idx.name}');");
      } else {
        _line("    t.index([$cols], name: '${idx.name}', unique: true);");
      }
    }
    _line('  });');
    _line('}');
    _line('');
  }

  /// Index columns are stored as *field* names; DDL needs DB names.
  String _dbName(TableSchema table, String field) =>
      table.columnByField(field)!.name;

  void _emitDropTable() {
    _line('/// Drops `${t.name}` (handy for tests).');
    _line('Future<void> drop${t.model}Table(Db db) async {');
    _line("  await db.dropTable('${t.name}');");
    _line('}');
    _line('');
  }

  void _emitRegisterRelations() {
    _line('/// Registers the `${t.name}` relationships on [db].');
    _line('void register${t.model}Relations(Db db) {');
    if (t.relations.isEmpty) {
      _line('  // No relations declared on ${t.model}.');
    } else {
      _line('  db.defineRelations([');
      for (final r in t.relations) {
        final factory = switch (r.kind) {
          RelationKind.hasMany => 'hasMany',
          RelationKind.hasOne => 'hasOne',
          RelationKind.belongsTo => 'belongsTo',
          RelationKind.belongsToMany => 'belongsToMany',
        };
        _line('    Relation.$factory(');
        _line("      name: '${r.name}',");
        _line("      fromTable: '${t.name}',");
        _line("      fromKey: '${r.localKey}',");
        switch (r.kind) {
          case RelationKind.hasMany:
          case RelationKind.hasOne:
            _line("      toTable: '${r.table}',");
            _line("      toKey: '${r.foreignKey}',");
          case RelationKind.belongsTo:
            _line("      toTable: '${r.table}',");
            _line("      toKey: '${r.targetKey}',");
          case RelationKind.belongsToMany:
            _line("      toTable: '${r.table}',");
            _line("      toKey: '${r.targetKey}',");
            _line("      pivotTable: '${r.pivot}',");
            _line("      pivotFromKey: '${r.pivotFromKey}',");
            _line("      pivotToKey: '${r.pivotToKey}',");
        }
        if (r.kind == RelationKind.hasMany) {
          if (r.orderBy != null) {
            _line("      orderBy: '${_dbName(_target(r), r.orderBy!)}',");
          }
          if (r.desc) _line('      desc: true,');
          if (r.limit != null) _line('      limit: ${r.limit},');
        }
        _line('    ),');
      }
      _line('  ]);');
    }
    _line('}');
    _line('');
  }

  void _emitHelpers() {
    // Per-model helper names: one .g.dart combines fragments for every
    // table, so a shared helper would collide.
    _line('Map<String, Object?> _withoutNulls${t.model}(Map<String, Object?> map) {');
    _line('  map.removeWhere((key, value) => value == null);');
    _line('  return map;');
    _line('}');
  }
}
